"""
GuiGazer — YOLOv8 Fine-Tuning Script
======================================
Fine-tunes ``yolov8n.pt`` on the synthetic GUI-element dataset generated by
:pymod:`detector.dataset`.  Saves the best checkpoint to
``detector/checkpoints/guigazer_yolov8n.pt`` and prints mAP metrics.

Run directly::

    python -m detector.train
    python -m detector.train --epochs 100 --batch 32
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from loguru import logger
from ultralytics import YOLO

# Resolve project root so ``config`` is always importable.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from config import settings  # noqa: E402
from detector.dataset import DATASET_DIR, download_rico_sample  # noqa: E402

# ── Defaults ──────────────────────────────────────────────────────────────────

DEFAULT_EPOCHS = 50
DEFAULT_BATCH = 16
DEFAULT_IMGSZ = 640
CHECKPOINT_DIR = Path(__file__).resolve().parent / "checkpoints"
BEST_WEIGHTS_NAME = "guigazer_yolov8n.pt"


def train(
    epochs: int = DEFAULT_EPOCHS,
    batch: int = DEFAULT_BATCH,
    imgsz: int = DEFAULT_IMGSZ,
    resume: bool = False,
) -> None:
    """Run the training loop.

    Parameters
    ----------
    epochs : int
        Number of training epochs.
    batch : int
        Batch size.
    imgsz : int
        Input image size (square).
    resume : bool
        If ``True``, resume from the last saved checkpoint.
    """
    # 1. Ensure dataset exists
    data_yaml = DATASET_DIR / "data.yaml"
    if not data_yaml.exists():
        logger.info("Dataset not found — generating synthetic GUI screenshots …")
        download_rico_sample(count=20)
    else:
        logger.info("Using existing dataset at {}", DATASET_DIR)

    # 2. Load base model
    base_model = "yolov8n.pt"
    logger.info("Loading base model: {}", base_model)
    model = YOLO(base_model)

    # 3. Train
    logger.info(
        "Starting training  |  epochs={}  |  batch={}  |  imgsz={}",
        epochs, batch, imgsz,
    )
    results = model.train(
        data=str(data_yaml),
        epochs=epochs,
        batch=batch,
        imgsz=imgsz,
        patience=10,
        save=True,
        project=str(_PROJECT_ROOT / "runs" / "detect"),
        name="guigazer",
        exist_ok=True,
        verbose=True,
    )

    # 4. Copy best weights to checkpoints/
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    best_src = Path(results.save_dir) / "weights" / "best.pt"
    best_dst = CHECKPOINT_DIR / BEST_WEIGHTS_NAME

    if best_src.exists():
        shutil.copy2(best_src, best_dst)
        logger.success("Best weights saved → {}", best_dst)
    else:
        # Fall back to last.pt if best.pt wasn't produced (e.g. very few epochs)
        last_src = Path(results.save_dir) / "weights" / "last.pt"
        if last_src.exists():
            shutil.copy2(last_src, best_dst)
            logger.warning("best.pt not found — copied last.pt → {}", best_dst)
        else:
            logger.error("No weights found in {}!", results.save_dir)
            return

    # 5. Validate & print metrics
    logger.info("Running validation …")
    model_best = YOLO(str(best_dst))
    metrics = model_best.val(data=str(data_yaml), imgsz=imgsz, verbose=False)

    logger.info("─── Validation Metrics ───")
    logger.info("  mAP50      : {:.4f}", metrics.box.map50)
    logger.info("  mAP50-95   : {:.4f}", metrics.box.map)
    logger.info("  Precision  : {:.4f}", metrics.box.mp)
    logger.info("  Recall     : {:.4f}", metrics.box.mr)

    # Per-class mAP50
    if hasattr(metrics.box, "maps") and metrics.box.maps is not None:
        from config import UI_CLASSES  # noqa: E402

        logger.info("  ── Per-class mAP50 ──")
        for cls_id, m in enumerate(metrics.box.maps):
            name = UI_CLASSES[cls_id] if cls_id < len(UI_CLASSES) else f"class_{cls_id}"
            logger.info("    {:20s}: {:.4f}", name, m)

    logger.success("Training complete ✓")


# ── CLI entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-tune YOLOv8 for GUI element detection")
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS, help="Training epochs")
    parser.add_argument("--batch", type=int, default=DEFAULT_BATCH, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=DEFAULT_IMGSZ, help="Image size")
    parser.add_argument("--resume", action="store_true", help="Resume from last checkpoint")
    args = parser.parse_args()

    train(epochs=args.epochs, batch=args.batch, imgsz=args.imgsz, resume=args.resume)
